name: JSON
on:
  push:
    branches:
      - main
    paths:
      - "**.json"
  pull_request:
    paths:
      - "**.json"
  workflow_dispatch:
jobs:
  lint:
    uses: parcelLab/.github/.github/workflows/json.yaml@main
