name: Prepare the release
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/*.yaml"
  workflow_dispatch:

jobs:
  release:
    uses: parcelLab/ci/.github/workflows/release.yaml@v8.3.7
    secrets:
      repoAccessToken: ${{ secrets.REPO_ACCESS_TOKEN_OPEN_SOURCE }}
