name: Docs
on:
  workflow_call:
    inputs:
      botEmail:
        required: false
        description: The email of the bot that will appear in the GitOps commit
        default: dev.bot@parcellab.com
        type: string
      botName:
        required: false
        description: The name of the bot that will appear in the GitOps commit
        default: parcellab-dev-bot
        type: string
      defaultBranch:
        required: false
        description: The default branch
        default: main
        type: string
      docsRepo:
        required: false
        description: The repository within Github that holds the central documentation files
        default: parcelLab/documentation
        type: string
    secrets:
      repoAccessToken:
        required: true
        description: The Github token to perform operations cross-repo (not github.token!)
jobs:
  jekyll:
    if: github.ref == 'refs/heads/${{ inputs.defaultBranch }}'
    runs-on: ubuntu-latest
    steps:
      - name: Load workflow variables
        id: vars
        run: |
          # shellcheck disable=SC2086
          echo "docs-push-folder=${{ github.workspace }}/remote/repos/${{ github.event.repository.name }}" >> $GITHUB_OUTPUT
      - name: Checkout current git repository
        uses: actions/checkout@v3
        with:
          path: this
      - name: Checkout ${{ inputs.docsRepo }} git repository
        uses: actions/checkout@v3
        with:
          path: remote
          ref: main
          repository: ${{ inputs.docsRepo }}
          token: ${{ secrets.repoAccessToken }}
      - name: Commit markdown files
        continue-on-error: true
        run: |
          rm -rf ${{ steps.vars.outputs.docs-push-folder }}
          mkdir -p ${{ steps.vars.outputs.docs-push-folder }}
          cd ${{ steps.vars.outputs.docs-push-folder }}
          git config --global user.email "${{ inputs.botEmail }}"
          git config --global user.name "${{ inputs.botName }}"
          rsync -am --prune-empty-dirs --include='*.md' --include='.assets/*' --include='*/' --exclude='*' ${{ github.workspace }}/this/${{ steps.vars.outputs.docs-push-folder }}
          git add -v .
          git commit -m "Update ${{ github.event.repository.name }} repo documentation"
      - name: Push changes to ${{ inputs.docsRepo }} git repository
        if: success()
        uses: ad-m/github-push-action@0fafdd62b84042d49ec0cb92d9cac7f7ce4ec79e
        with:
          directory: ${{ steps.vars.outputs.docs-push-folder }}
          repository: ${{ inputs.docsRepo }}
          github_token: ${{ secrets.repoAccessToken }}
          branch: ${{ inputs.defaultBranch }}
          force: true
