name: Reusable JSON
on:
  workflow_call:
    inputs:
      runner:
        required: false
        description: Runner type
        default: ubuntu-latest
        type: string
      timeoutMinutes:
        required: false
        description: Maximum minutes before the job is cancelled
        default: 40
        type: number
jobs:
  json:
    runs-on: ${{ inputs.runner }}
    timeout-minutes: ${{ inputs.timeoutMinutes }}
    steps:
      - name: Checkout current git repository
        uses: actions/checkout@v7
      - name: Lint JSON
        uses: actionsx/prettier@v3
        with:
          args: --check "**/*.json"
