name: Reusable Update Main Version
on:
  workflow_call:
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Load version
        id: vars
        run: |
          TAG_NAME="${{ github.ref }}"
          CLEAN_TAG=${TAG_NAME##*/}
          SHORT_VERSION=${CLEAN_TAG%%.*}
          # shellcheck disable=SC2086
          echo "shortVersion=$SHORT_VERSION" >> $GITHUB_OUTPUT
      - name: Git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Tag new target
        run: |
          # shellcheck disable=SC2086,SC2296
          git tag -f ${{ steps.vars.outputs.shortVersion }} ${{ github.ref }}
      - name: Push new tag
        run: |
          # shellcheck disable=SC2086
          git push origin ${{ steps.vars.outputs.shortVersion }} --force
