name: Reusable parcelLab Config
on:
  workflow_call:
    inputs:
      botEmail:
        required: false
        description: The email of the bot that will appear in the GitOps commit
        default: dev.bot@parcellab.com
        type: string
      botName:
        required: false
        description: The name of the bot that will appear in the GitOps commit
        default: parcellab-dev-bot
        type: string
      configurationFilepath:
        required: false
        description: The path to the application configuration file
        default: ./plconfig.yaml
        type: string
      deploymentRepoPath:
        required: false
        description: The path within the deployment repository that holds all version files
        default: namespaces
        type: string
      deploymentRepoURL:
        required: false
        description: The repository within Github that holds the version file to deploy via GitOps
        default: parcelLab/deployment
        type: string
    secrets:
      repoAccessToken:
        required: true
        description: The Github token to perform operations cross-repo (not secrets.GITHUB_TOKEN!)
jobs:
  read_schema_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.result }}
    steps:
      - name: Checkout current git repository
        uses: actions/checkout@v3
      - name: Load schema version
        id: version
        uses: mikefarah/yq@v4.30.8
        with:
          cmd: yq ".schemaVersion" ${{ inputs.configurationFilepath }}
  plconfig_legacy:
    runs-on: ubuntu-latest
    needs: [read_schema_version]
    if: needs.read_schema_version.outputs.version != 'v2'
    steps:
      - name: Checkout current git repository
        uses: actions/checkout@v3
      - name: Load name
        id: name
        uses: mikefarah/yq@v4.30.8
        with:
          cmd: yq ".deployment.name" ${{ inputs.configurationFilepath }}
      - name: Load namespace
        id: namespace
        uses: mikefarah/yq@v4.30.8
        with:
          cmd: yq ".deployment.namespace" ${{ inputs.configurationFilepath }}
      - name: Load chart
        id: chart
        uses: mikefarah/yq@v4.30.8
        with:
          cmd: yq ".deployment.chart" ${{ inputs.configurationFilepath }}
      - name: Checkout ${{ inputs.deploymentRepoURL }} git repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.deploymentRepoURL }}
          path: remote
          token: ${{ secrets.repoAccessToken }}
          ref: main
      - name: Load vars
        id: vars
        run: |
          # shellcheck disable=SC2086
          echo "namespace-path=remote/${{ inputs.deploymentRepoPath }}/${{ steps.namespace.outputs.result }}" >> $GITHUB_OUTPUT
          # shellcheck disable=SC2086
          echo "do-not-edit=DO NOT EDIT. Auto generated from ${{ steps.name.outputs.result }} ${{ inputs.configurationFilepath }} (replaces values.yaml instead)" >> $GITHUB_OUTPUT
      # Load plconfig values scoping to a subchart
      - name: Load external values for all environments
        uses: mikefarah/yq@v4.30.8
        with:
          cmd: >-
            $(yq '.deployment.values | has("dev")' ${{ inputs.configurationFilepath }}) == 'true' && yq '{ "${{ steps.chart.outputs.result }}": .deployment.values.dev } | . head_comment="${{ steps.vars.outputs.do-not-edit }}"' ${{ inputs.configurationFilepath }} > ${{ steps.vars.outputs.namespace-path }}/dev/${{ steps.name.outputs.result }}/values-external.yaml ||
            $(yq '.deployment.values | has("prod")' ${{ inputs.configurationFilepath }}) == 'true' && yq '{ "${{ steps.chart.outputs.result }}": .deployment.values.prod } | . head_comment="${{ steps.vars.outputs.do-not-edit }}"' ${{ inputs.configurationFilepath }} > ${{ steps.vars.outputs.namespace-path }}/prod/${{ steps.name.outputs.result }}/values-external.yaml ||
            $(yq '.deployment.values | has("staging")' ${{ inputs.configurationFilepath }}) == 'true' && yq '{ "${{ steps.chart.outputs.result }}": .deployment.values.staging } | . head_comment="${{ steps.vars.outputs.do-not-edit }}"' ${{ inputs.configurationFilepath }} > ${{ steps.vars.outputs.namespace-path }}/staging/${{ steps.name.outputs.result }}/values-external.yaml ||
            $(yq '.deployment.values | has("test")' ${{ inputs.configurationFilepath }}) == 'true' && yq '{ "${{ steps.chart.outputs.result }}": .deployment.values.test } | . head_comment="${{ steps.vars.outputs.do-not-edit }}"' ${{ inputs.configurationFilepath }} > ${{ steps.vars.outputs.namespace-path }}/test/${{ steps.name.outputs.result }}/values-external.yaml || true
      # Commit & Push
      - name: Commit deployment files
        run: |
          cd remote
          git config --global user.email "${{ inputs.botEmail }}"
          git config --global user.name "${{ inputs.botName }}"
          git add .
          git commit --allow-empty -m "chore(${{ steps.name.outputs.result }}): set parcelLab config values"
      - name: Push changes to main in ${{ inputs.deploymentRepoURL }} git repository
        uses: ad-m/github-push-action@0fafdd62b84042d49ec0cb92d9cac7f7ce4ec79e
        with:
          repository: ${{ inputs.deploymentRepoURL }}
          directory: remote
          github_token: ${{ secrets.repoAccessToken }}
          branch: main
          force: true
  detect_declarations:
    runs-on: ubuntu-latest
    needs: [read_schema_version]
    if: needs.read_schema_version.outputs.version == 'v2'
    outputs:
      has-kubernetes: ${{ steps.has-kubernetes.outputs.result }}
    steps:
      - name: Checkout current git repository
        uses: actions/checkout@v3
      - name: Detect kubernetes deployment
        id: has-kubernetes
        uses: mikefarah/yq@v4.30.8
        with:
          cmd: yq '.deployment | has("kubernetes")' ${{ inputs.configurationFilepath }}
  kubernetes_values:
    runs-on: ubuntu-latest
    needs: [detect_declarations]
    if: needs.detect_declarations.outputs.has-kubernetes == 'true'
    steps:
      - name: Checkout current git repository
        uses: actions/checkout@v3
      - name: Checkout ${{ inputs.deploymentRepoURL }} git repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.deploymentRepoURL }}
          path: remote
          token: ${{ secrets.repoAccessToken }}
          ref: main
      - name: Load YAML values from file into JSON
        id: json
        uses: mikefarah/yq@v4.30.8
        with:
          cmd: yq "." ${{ inputs.configurationFilepath }} -o=json -I=0
      - name: Detect values for dev environment
        id: has-dev-values
        uses: mikefarah/yq@v4.30.8
        with:
          cmd: yq '.deployment.kubernetes.env.dev | has("values")' ${{ inputs.configurationFilepath }}
      - name: Detect values for prod environment
        id: has-prod-values
        uses: mikefarah/yq@v4.30.8
        with:
          cmd: yq '.deployment.kubernetes.env.prod | has("values")' ${{ inputs.configurationFilepath }}
      - name: Detect values for staging environment
        id: has-staging-values
        uses: mikefarah/yq@v4.30.8
        with:
          cmd: yq '.deployment.kubernetes.env.staging | has("values")' ${{ inputs.configurationFilepath }}
      - name: Detect values for test environment
        id: has-test-values
        uses: mikefarah/yq@v4.30.8
        with:
          cmd: yq '.deployment.kubernetes.env.test | has("values")' ${{ inputs.configurationFilepath }}
      - name: Load common vars
        id: vars
        run: |
          # shellcheck disable=SC2086
          echo "namespace-path=remote/${{ inputs.deploymentRepoPath }}/${{ fromJSON(steps.json.outputs.result).deployment.kubernetes.namespace }}" >> $GITHUB_OUTPUT
          # shellcheck disable=SC2086
          echo "do-not-edit=DO NOT EDIT. Auto generated from ${{ fromJSON(steps.json.outputs.result).name }} ${{ inputs.configurationFilepath }} (replaces values.yaml instead)" >> $GITHUB_OUTPUT
      - if: steps.has-dev-values.outputs.result == 'true'
        name: Load external values for dev
        uses: mikefarah/yq@v4.30.8
        with:
          cmd: >-
            yq '.deployment.kubernetes.env.dev.values | . head_comment="${{ steps.vars.outputs.do-not-edit }}"' ${{ inputs.configurationFilepath }} > ${{ steps.vars.outputs.namespace-path }}/dev/${{ fromJSON(steps.json.outputs.result).name }}/values-external.yaml
      - if: steps.has-prod-values.outputs.result == 'true'
        name: Load external values for prod
        uses: mikefarah/yq@v4.30.8
        with:
          cmd: >-
            yq '.deployment.kubernetes.env.prod.values | . head_comment="${{ steps.vars.outputs.do-not-edit }}"' ${{ inputs.configurationFilepath }} > ${{ steps.vars.outputs.namespace-path }}/prod/${{ fromJSON(steps.json.outputs.result).name }}/values-external.yaml
      - if: steps.has-staging-values.outputs.result == 'true'
        name: Load external values for staging
        uses: mikefarah/yq@v4.30.8
        with:
          cmd: >-
            yq '.deployment.kubernetes.env.staging.values | . head_comment="${{ steps.vars.outputs.do-not-edit }}"' ${{ inputs.configurationFilepath }} > ${{ steps.vars.outputs.namespace-path }}/staging/${{ fromJSON(steps.json.outputs.result).name }}/values-external.yaml
      - if: steps.has-test-values.outputs.result == 'true'
        name: Load external values for test
        uses: mikefarah/yq@v4.30.8
        with:
          cmd: >-
            yq '.deployment.kubernetes.env.test.values | . head_comment="${{ steps.vars.outputs.do-not-edit }}"' ${{ inputs.configurationFilepath }} > ${{ steps.vars.outputs.namespace-path }}/test/${{ fromJSON(steps.json.outputs.result).name }}/values-external.yaml
      # Commit & Push to GitOps repo
      - name: Commit deployment files
        run: |
          cd remote
          git config --global user.email "${{ inputs.botEmail }}"
          git config --global user.name "${{ inputs.botName }}"
          git add .
          git commit --allow-empty -m "chore(${{ fromJSON(steps.json.outputs.result).name }}): set parcelLab config values"
      - name: Push changes to main in ${{ inputs.deploymentRepoURL }} git repository
        uses: ad-m/github-push-action@0fafdd62b84042d49ec0cb92d9cac7f7ce4ec79e
        with:
          repository: ${{ inputs.deploymentRepoURL }}
          directory: remote
          github_token: ${{ secrets.repoAccessToken }}
          branch: main
          force: true
