name: Reusable Shell
on:
  workflow_call:
    inputs:
      findCommandExtraArgs:
        required: false
        description: Pass extra arguments to the find command (e.g. '! -path "*/.terraform*"'' to exclude patterns in the .terraform subfolder from the tree)
        type: string
      runner:
        required: false
        description: Runner type
        default: ubuntu-latest
        type: string
jobs:
  shell:
    runs-on: ${{ inputs.runner }}
    container: koalaman/shellcheck-alpine:v0.9.0
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
      - name: Check shell scripts
        run: 'find . -type f \( -name "*.sh" \) ${{ inputs.findCommandExtraArgs }} -print | while IFS="" read -r file; do shellcheck "$file"; done;'
