name: Reusable YAML
on:
  workflow_call:
    inputs:
      runner:
        required: false
        description: Runner type
        default: ubuntu-latest
        type: string
      args:
        required: false
        description: List of yaml files to include
        default: "**/*.{yaml,yml}"
        type: string
      excluded_args:
        required: false
        description: List of yaml files to exclude
        default: ""
        type: string
jobs:
  yaml:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout current git repository
        uses: actions/checkout@v3
      - name: Lint YAML
        uses: actionsx/prettier@v2
        with:
          args: --check "${{ inputs.args }}" "${{ inputs.excluded_args }}"
