name: Reusable YAML
on:
  workflow_call:
    inputs:
      runner:
        required: false
        description: Runner type
        default: ubuntu-latest
        type: string
      additional_args:
        required: false
        description: List of yaml files to exclude
        type: string
      format:
        required: false
        description: Run prettier with write argument
        default: false
        type: boolean
jobs:
  yaml:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout current git repository
        uses: actions/checkout@v3

      - name: Check linting all YAML files
        uses: actionsx/prettier@v3
        if: (${{ inputs.additional_args == '' }}) && (${{ !inputs.format }})
        with:
          args: --check "**/*.{yaml,yml}"

      - name: Linting all YAML files
        uses: actionsx/prettier@v3
        if: (${{ inputs.additional_args == '' }}) && (${{ inputs.format }})
        with:
          args: --write "**/*.{yaml,yml}"

      - name: Check linting of some YAML files
        uses: actionsx/prettier@v3
        if: (${{ inputs.additional_args != '' }}) && (${{ !inputs.format }})
        with:
          args: --check "**/*.{yaml,yml}" "${{ inputs.additional_args }}"

      - name: Linting some YAML files
        uses: actionsx/prettier@v3
        if: (${{ inputs.additional_args != '' }}) && (${{ inputs.format }})
        with:
          args: --write "**/*.{yaml,yml}" "${{ inputs.additional_args }}"
